package com.mcp.server.domain.client.dto.public_api.response;

/**
 * Represents a single choice returned by the OpenAI Chat API.
 * <p>
 * Each choice contains the message generated by the model, its index, and
 * a finish reason indicating why the message ended.
 * </p>
 *
 * @param index         the index of this choice in the response list
 * @param message       the generated message as a {@link Message} object
 * @param finish_reason the reason why the generation finished (e.g., "stop", "length")
 */
public record Choice(
        int index,
        Message message,
        String finish_reason
) {}
